lib{double-conversion}: libul{double-conversion}: {hxx cxx}{**}

# Export all symbols from the DLL if on Windows.
#
libs{double-conversion}: def{double-conversion}: \
  include = ($cxx.target.system == 'win32-msvc')

def{double-conversion}: libul{double-conversion}

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{double-conversion}: cxx.export.poptions = "-I$src_root"

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{double-conversion}: bin.lib.version = "-$version.project_id"
else
  lib{double-conversion}: bin.lib.version = "-$version.major.$version.minor"

# Install into the double-conversion/ subdirectory of, say, /usr/include/.
#
hxx{*}:              install = include/double-conversion/
hxx{bignum-dtoa}@./: install = false # Exclude the sole private header.
